In [114]:
import numpy as np

In [115]:
import pandas as pd

In [116]:
movies=pd.read_csv('tmdb_5000_movies.csv')
credits=pd.read_csv('tmdb_5000_credits.csv')

In [117]:
movies.head(1)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800

In [118]:
credits.head()

,movie_id,title,cast,crew
0,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [119]:
movies= movies.merge(credits,on='title')

In [120]:
movies.head()

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,...,runtime,spoken_languages,status,tagline,title,vote_average,vote_count,movie_id,cast,crew
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...",...,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,19995,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...",...,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500,285,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...",...,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466,206647,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...",...,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106,49026,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]",...,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124,49529,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [121]:
#genres
#id
#keywords
#title
#overview
#cast
#crew
movies=movies[['movie_id','title','overview','genres','keywords','cast','crew']]

In [122]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [123]:

movies.isnull().sum()

movie_id    0
title       0
overview    3
genres      0
keywords    0
cast        0
crew        0
dtype: int64

In [124]:
movies.dropna(inplace=True)

In [125]:
movies.duplicated().sum()

np.int64(0)

In [126]:
movies.iloc[0].genres

'[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]'

In [127]:
import ast
def convert(obj):
    L=[]
    for i in ast.literal_eval(obj):
        L.append(i['name'])
    return L

In [128]:
movies['genres']=movies['genres'].apply(convert)

In [129]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[Action, Adventure, Crime]","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [130]:
movies['keywords']=movies['keywords'].apply(convert)

In [131]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [132]:
def convert3(obj):
    L=[]
    counter=0
    for i in ast.literal_eval(obj):
        if counter!=3:
            L.append(i['name'])
            counter+=1
        else:
            break
    return L

In [133]:
movies['cast']=movies['cast'].apply(convert3)

In [134]:
movies['cast'].head

<bound method NDFrame.head of 0        [Sam Worthington, Zoe Saldana, Sigourney Weaver]
1           [Johnny Depp, Orlando Bloom, Keira Knightley]
2            [Daniel Craig, Christoph Waltz, Léa Seydoux]
3            [Christian Bale, Michael Caine, Gary Oldman]
4          [Taylor Kitsch, Lynn Collins, Samantha Morton]
                              ...
4804    [Carlos Gallardo, Jaime de Hoyos, Peter Marqua...
4805         [Edward Burns, Kerry Bishé, Marsha Dietlein]
4806           [Eric Mabius, Kristin Booth, Crystal Lowe]
4807            [Daniel Henney, Eliza Coupe, Bill Paxton]
4808    [Drew Barrymore, Brian Herzlinger, Corey Feldman]
Name: cast, Length: 4806, dtype: object>

In [135]:
def fetch_director(obj):
    L=[]
    
    for i in ast.literal_eval(obj):
        if i['job']=='Director':
            L.append(i['name'])
            break
        
    return L

movies['crew']=movies['crew'].apply(fetch_director)

In [136]:
movies['crew'].head()

0    [{"credit_id": "52fe48009251416c750aca23", "de...
1    [{"credit_id": "52fe4232c3a36847f800b579", "de...
2    [{"credit_id": "54805967c3a36829b5002c41", "de...
3    [{"credit_id": "52fe4781c3a36847f81398c3", "de...
4    [{"credit_id": "52fe479ac3a36847f813eaa3", "de...
Name: crew, dtype: object

In [137]:
movies['overview']=movies['overview'].apply(lambda x:x.split())

In [138]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley]","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send...","[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[Daniel Craig, Christoph Waltz, Léa Seydoux]","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[Christian Bale, Michael Caine, Gary Oldman]","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[Taylor Kitsch, Lynn Collins, Samantha Morton]","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [139]:
movies['genres']=movies['genres'].apply(lambda x:[i.replace(" ","") for i in x])
movies['keywords']=movies['keywords'].apply(lambda x:[i.replace(" ","") for i in x])
movies['cast']=movies['cast'].apply(lambda x:[i.replace(" ","") for i in x])
movies['crew']=movies['crew'].apply(lambda x:[i.replace(" ","") for i in x])

In [140]:
movies['tags']=movies['overview']+movies['genres']+movies['keywords']+movies['cast']+movies['crew']

In [141]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew,tags
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, ScienceFiction]","[cultureclash, future, spacewar, spacecolony, ...","[SamWorthington, ZoeSaldana, SigourneyWeaver]","[[, {, "", c, r, e, d, i, t, _, i, d, "", :, , ""...","[In, the, 22nd, century,, a, paraplegic, Marin..."
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[ocean, drugabuse, exoticisland, eastindiatrad...","[JohnnyDepp, OrlandoBloom, KeiraKnightley]","[[, {, "", c, r, e, d, i, t, _, i, d, "", :, , ""...","[Captain, Barbossa,, long, believed, to, be, d..."
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send...","[Action, Adventure, Crime]","[spy, basedonnovel, secretagent, sequel, mi6, ...","[DanielCraig, ChristophWaltz, LéaSeydoux]","[[, {, "", c, r, e, d, i, t, _, i, d, "", :, , ""...","[A, cryptic, message, from, Bond’s, past, send..."
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[Action, Crime, Drama, Thriller]","[dccomics, crimefighter, terrorist, secretiden...","[ChristianBale, MichaelCaine, GaryOldman]","[[, {, "", c, r, e, d, i, t, _, i, d, "", :, , ""...","[Following, the, death, of, District, Attorney..."
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[Action, Adventure, ScienceFiction]","[basedonnovel, mars, medallion, spacetravel, p...","[TaylorKitsch, LynnCollins, SamanthaMorton]","[[, {, "", c, r, e, d, i, t, _, i, d, "", :, , ""...","[John, Carter, is, a, war-weary,, former, mili..."

In [142]:
new_df=movies[['movie_id','title','tags']]

In [143]:
new_df['tags']=new_df['tags'].apply(lambda x:" ".join(x))

C:\Users\HP\AppData\Local\Temp\ipykernel_10676\487797088.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags']=new_df['tags'].apply(lambda x:" ".join(x))

In [144]:
new_df['tags']=new_df['tags'].apply(stem)

C:\Users\HP\AppData\Local\Temp\ipykernel_10676\3514595201.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags']=new_df['tags'].apply(stem)

In [145]:
new_df['tags'][0]

'in the 22nd century, a parapleg marin is dispatch to the moon pandora on a uniqu mission, but becom torn between follow order and protect an alien civilization. action adventur fantasi sciencefict cultureclash futur spacewar spacecoloni societi spacetravel futurist romanc space alien tribe alienplanet cgi marin soldier battl loveaffair antiwar powerrel mindandsoul 3d samworthington zoesaldana sigourneyweav [ { " c r e d i t _ i d " : " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 2 3 " , " d e p a r t m e n t " : " e d i t i n g " , " g e n d e r " : 0 , " i d " : 1 7 2 1 , " j o b " : " e d i t o r " , " n a m e " : " s t e p h e n e . r i v k i n " } , { " c r e d i t _ i d " : " 5 3 9 c 4 7 e c c 3 a 3 6 8 1 0 e 3 0 0 1 f 8 7 " , " d e p a r t m e n t " : " a r t " , " g e n d e r " : 2 , " i d " : 4 9 6 , " j o b " : " p r o d u c t i o n d e s i g n " , " n a m e " : " r i c k c a r t e r " } , { " c r e d i t _ i d " : " 5 4 4 9 1 c 8 9 c 3 a 3 6 8 0 f b 4 0 0 1 c f 7 " , " d e p a r t m e n t " : " s o u n d " , " g e n d e r " : 0 , " i d " : 9 0 0 , " j o b " : " s o u n d d e s i g n e r " , " n a m e " : " c h r i s t o p h e r b o y e s " } , { " c r e d i t _ i d " : " 5 4 4 9 1 c b 7 0 e 0 a 2 6 7 4 8 0 0 0 1 b d 0 " , " d e p a r t m e n t " : " s o u n d " , " g e n d e r " : 0 , " i d " : 9 0 0 , " j o b " : " s u p e r v i s i n g s o u n d e d i t o r " , " n a m e " : " c h r i s t o p h e r b o y e s " } , { " c r e d i t _ i d " : " 5 3 9 c 4 a 4 c c 3 a 3 6 8 1 0 c 9 0 0 2 1 0 1 " , " d e p a r t m e n t " : " p r o d u c t i o n " , " g e n d e r " : 1 , " i d " : 1 2 6 2 , " j o b " : " c a s t i n g " , " n a m e " : " m a l i f i n n " } , { " c r e d i t _ i d " : " 5 5 4 4 e e 3 b 9 2 5 1 4 1 4 9 9 f 0 0 0 8 f c " , " d e p a r t m e n t " : " s o u n d " , " g e n d e r " : 2 , " i d " : 1 7 2 9 , " j o b " : " o r i g i n a l m u s i c c o m p o s e r " , " n a m e " : " j a m e s h o r n e r " } , { " c r e d i t _ i d " : " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c 9 c 3 " , " d e p a r t m e n t " : " d i r e c t i n g " , " g e n d e r " : 2 , " i d " : 2 7 1 0 , " j o b " : " d i r e c t o r " , " n a m e " : " j a m e s c a m e r o n " } , { " c r e d i t _ i d " : " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c 9 d 9 " , " d e p a r t m e n t " : " w r i t i n g " , " g e n d e r " : 2 , " i d " : 2 7 1 0 , " j o b " : " w r i t e r " , " n a m e " : " j a m e s c a m e r o n " } , { " c r e d i t _ i d " : " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 1 7 " , " d e p a r t m e n t " : " e d i t i n g " , " g e n d e r " : 2 , " i d " : 2 7 1 0 , " j o b " : " e d i t o r " , " n a m e " : " j a m e s c a m e r o n " } , { " c r e d i t _ i d " : " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 2 9 " , " d e p a r t m e n t " : " p r o d u c t i o n " , " g e n d e r " : 2 , " i d " : 2 7 1 0 , " j o b " : " p r o d u c e r " , " n a m e " : " j a m e s c a m e r o n " } , { " c r e d i t _ i d " : " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 3 f " , " d e p a r t m e n t " : " w r i t i n g " , " g e n d e r " : 2 , " i d " : 2 7 1 0 , " j o b " : " s c r e e n p l a y " , " n a m e " : " j a m e s c a m e r o n " } , { " c r e d i t _ i d " : " 5 3 9 c 4 9 8 7 c 3 a 3 6 8 1 0 b a 0 0 2 1 a 4 " , " d e p a r t m e n t " : " a r t " , " g e n d e r " : 2 , " i d " : 7 2 3 6 , " j o b " : " a r t d i r e c t i o n " , " n a m e " : " a n d r e w m e n z i e s " } , { " c r e d i t _ i d " : " 5 4 9 5 9 8 c 3 c 3 a 3 6 8 6 a e 9 0 0 4 3 8 3 " , " d e p a r t m e n t " : " v i s u a l e f f e c t s " , " g e n d e r " : 0 , " i d " : 6 6 9 0 , " j o b " : " v i s u a l e f f e c t s p r o d u c e r " , " n a m e " : " j i l l b r o o k s " } , { " c r e d i t _ i d " : " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 4 b " , " d e p a r t m e n t " : " p r o d u c t i o n " , " g e n d e r " : 1 , " i d " : 6 3 4 7 , " j o b " : " c a s t i n g " , " n a m e " : " m a r g e r y s i m k i n " } , { " c r e d i t _ i d " : " 5 7 0 b 6 f 4 1 9 2 5 1 4 1 7 d a 7 0 0 3 2 f e " , " d e p a r t m e n t " : " a r t " , " g e n d e r " : 2 , " i d " : 6 8 7 8 , " j o b " : " s u p e r v i s i n g a r t d i r e c t o r " , " n a m e " : " k e v i n i s h i o k a " } , { " c r e d i t _ i d " : " 5 4 9 5 a 0 f a c 3 a 3 6 8 6 a e 9 0 0 4 4 6 8 " , " d e p a r t m e n t " : " s o u n d " , " g e n d e r " : 0 , " i d " : 6 8 8 3 , " j o b " : " m u s i c e d i t o r " , " n a m e " : " d i c k b e r n s t e i n " } , { " c r e d i t _ i d " : " 5 4 9 5 9 7 0 6 c 3 a 3 6 8 6 a f 3 0 0 3 e 8 1 " , " d e p a r t m e n t " : " s o u n d " , " g e n d e r " : 0 , " i d " : 8 1 5 9 , " j o b " : " s o u n d e f f e c t s e d i t o r " , " n a m e " : " s h a n n o n m i l l s " } , { " c r e d i t _ i d " : " 5 4 4 9 1 d 5 8 c 3 a 3 6 8 0 f b 1 0 0 1 c c b " , " d e p a r t m e n t " : " s o u n d " , " g e n d e r " : 0 , " i d " : 8 1 6 0 , " j o b " : " f o l e y " , " n a m e " : " d e n n i e t h o r p e " } , { " c r e d i t _ i d " : " 5 4 4 9 1 d 6 c c 3 a 3 6 8 0 f a 5 0 0 1 b 2 c " , " d e p a r t m e n t " : " s o u n d " , " g e n d e r " : 0 , " i d " : 8 1 6 3 , " j o b " : " f o l e y " , " n a m e " : " j a n a v a n c e " } , { " c r e d i t _ i d " : " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 5 7 " , " d e p a r t m e n t " : " c o s t u m e & m a k e - u p " , " g e n d e r " : 1 , " i d " : 8 5 2 7 , " j o b " : " c o s t u m e d e s i g n " , " n a m e " : " d e b o r a h l y n n s c o t t " } , { " c r e d i t _ i d " : " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 2 f " , " d e p a r t m e n t " : " p r o d u c t i o n " , " g e n d e r " : 2 , " i d " : 8 5 2 9 , " j o b " : " p r o d u c e r " , " n a m e " : " j o n l a n d a u " } , { " c r e d i t _ i d " : " 5 3 9 c 4 9 3 7 c 3 a 3 6 8 1 0 b a 0 0 2 1 9 4 " , " d e p a r t m e n t " : " a r t " , " g e n d e r " : 0 , " i d " : 9 6 1 8 , " j o b " : " a r t d i r e c t i o n " , " n a m e " : " s e a n h a w o r t h " } , { " c r e d i t _ i d " : " 5 3 9 c 4 9 b 6 c 3 a 3 6 8 1 0 c 1 0 0 2 0 e 6 " , " d e p a r t m e n t " : " a r t " , " g e n d e r " : 1 , " i d " : 1 2 6 5 3 , " j o b " : " s e t d e c o r a t i o n " , " n a m e " : " k i m s i n c l a i r " } , { " c r e d i t _ i d " : " 5 7 0 b 6 f 2 f 9 2 5 1 4 1 3 a 0 e 0 0 0 2 0 d " , " d e p a r t m e n t " : " a r t " , " g e n d e r " : 1 , " i d " : 1 2 6 5 3 , " j o b " : " s u p e r v i s i n g a r t d i r e c t o r " , " n a m e " : " k i m s i n c l a i r " } , { " c r e d i t _ i d " : " 5 4 4 9 1 a 6 c 0 e 0 a 2 6 7 4 8 c 0 0 1 b 1 9 " , " d e p a r t m e n t " : " a r t " , " g e n d e r " : 2 , " i d " : 1 4 3 5 0 , " j o b " : " s e t d e s i g n e r " , " n a m e " : " r i c h a r d f . m a y s " } , { " c r e d i t _ i d " : " 5 6 9 2 8 c f 4 c 3 a 3 6 8 4 c f f 0 0 2 5 c 4 " , " d e p a r t m e n t " : " p r o d u c t i o n " , " g e n d e r " : 1 , " i d " : 2 0 2 9 4 , " j o b " : " e x e c u t i v e p r o d u c e r " , " n a m e " : " l a e t a k a l o g r i d i s " } , { " c r e d i t _ i d " : " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 5 1 " , " d e p a r t m e n t " : " c o s t u m e & m a k e - u p " , " g e n d e r " : 0 , " i d " : 1 7 6 7 5 , " j o b " : " c o s t u m e d e s i g n " , " n a m e " : " m a y e s c . r u b e o " } , { " c r e d i t _ i d " : " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 1 1 " , " d e p a r t m e n t " : " c a m e r a " , " g e n d e r " : 2 , " i d " : 1 8 2 6 5 , " j o b " : " d i r e c t o r o f p h o t o g r a p h y " , " n a m e " : " m a u r o f i o r e " } , { " c r e d i t _ i d " : " 5 4 4 9 1 9 4 d 0 e 0 a 2 6 7 4 8 f 0 0 1 b 3 9 " , " d e p a r t m e n t " : " a r t " , " g e n d e r " : 0 , " i d " : 4 2 2 8 1 , " j o b " : " s e t d e s i g n e r " , " n a m e " : " s c o t t h e r b e r t s o n " } , { " c r e d i t _ i d " : " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 0 5 " , " d e p a r t m e n t " : " c r e w " , " g e n d e r " : 0 , " i d " : 4 2 2 8 8 , " j o b " : " s t u n t s " , " n a m e " : " w o o d y s c h u l t z " } , { " c r e d i t _ i d " : " 5 5 9 2 a e f b 9 2 5 1 4 1 5 2 d e 0 0 1 0 f 5 " , " d e p a r t m e n t " : " c o s t u m e & m a k e - u p " , " g e n d e r " : 0 , " i d " : 2 9 0 6 7 , " j o b " : " m a k e u p a r t i s t " , " n a m e " : " l i n d a d e v e t t a " } , { " c r e d i t _ i d " : " 5 5 9 2 a f a 4 9 2 5 1 4 1 5 2 d e 0 0 1 1 2 c " , " d e p a r t m e n t " : " c o s t u m e & m a k e - u p " , " g e n d e r " : 0 , " i d " : 2 9 0 6 7 , " j o b " : " h a i r s t y l i s t " , " n a m e " : " l i n d a d e v e t t a " } , { " c r e d i t _ i d " : " 5 4 9 5 9 e d 5 9 2 5 1 4 1 3 0 f c 0 0 2 e 5 d " , " d e p a r t m e n t " : " c a m e r a " , " g e n d e r " : 2 , " i d " : 3 3 3 0 2 , " j o b " : " c a m e r a o p e r a t o r " , " n a m e " : " r i c h a r d b l u c k " } , { " c r e d i t _ i d " : " 5 3 9 c 4 8 9 1 c 3 a 3 6 8 1 0 b a 0 0 2 1 4 7 " , " d e p a r t m e n t " : " a r t " , " g e n d e r " : 2 , " i d " : 3 3 3 0 3 , " j o b " : " a r t d i r e c t i o n " , " n a m e " : " s i m o n b r i g h t " } , { " c r e d i t _ i d " : " 5 4 9 5 9 c 0 6 9 2 5 1 4 1 7 a 8 1 0 0 1 f 3 a " , " d e p a r t m e n t " : " v i s u a l e f f e c t s " , " g e n d e r " : 0 , " i d " : 1 1 3 1 4 5 , " j o b " : " v i s u a l e f f e c t s s u p e r v i s o r " , " n a m e " : " r i c h a r d m a r t i n " } , { " c r e d i t _ i d " : " 5 4 9 5 9 a 0 d c 3 a 3 6 8 0 f f 5 0 0 2 c 8 d " , " d e p a r t m e n t " : " c r e w " , " g e n d e r " : 2 , " i d " : 5 8 1 8 8 , " j o b " : " v i s u a l e f f e c t s e d i t o r " , " n a m e " : " s t e v e r . m o o r e " } , { " c r e d i t _ i d " : " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 1 d " , " d e p a r t m e n t " : " e d i t i n g " , " g e n d e r " : 2 , " i d " : 5 8 8 7 1 , " j o b " : " e d i t o r " , " n a m e " : " j o h n r e f o u a " } , { " c r e d i t _ i d " : " 5 4 4 9 1 a 4 d c 3 a 3 6 8 0 f c 3 0 0 1 8 c a " , " d e p a r t m e n t " : " a r t " , " g e n d e r " : 0 , " i d " : 9 2 3 5 9 , " j o b " : " s e t d e s i g n e r " , " n a m e " : " k a r l j . m a r t i n " } , { " c r e d i t _ i d " : " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 3 5 " , " d e p a r t m e n t " : " c a m e r a " , " g e n d e r " : 1 , " i d " : 7 2 2 0 1 , " j o b " : " d i r e c t o r o f p h o t o g r a p h y " , " n a m e " : " c h i l i n g l i n " } , { " c r e d i t _ i d " : " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c 9 f f " , " d e p a r t m e n t " : " c r e w " , " g e n d e r " : 0 , " i d " : 8 9 7 1 4 , " j o b " : " s t u n t s " , " n a m e " : " i l r a m c h o i " } , { " c r e d i t _ i d " : " 5 4 9 5 9 c 5 2 9 2 5 1 4 1 6 e 2 b 0 0 4 3 9 4 " , " d e p a r t m e n t " : " v i s u a l e f f e c t s " , " g e n d e r " : 2 , " i d " : 9 3 2 1 4 , " j o b " : " v i s u a l e f f e c t s s u p e r v i s o r " , " n a m e " : " s t e v e n q u a l e " } , { " c r e d i t _ i d " : " 5 4 4 9 1 e d f 0 e 0 a 2 6 7 4 8 9 0 0 1 c 3 7 " , " d e p a r t m e n t " : " c r e w " , " g e n d e r " : 1 , " i d " : 1 2 2 6 0 7 , " j o b " : " d i a l e c t c o a c h " , " n a m e " : " c a r l a m e y e r " } , { " c r e d i t _ i d " : " 5 3 9 c 4 8 5 b c 3 a 3 6 8 6 5 3 d 0 0 1 a 3 a " , " d e p a r t m e n t " : " a r t " , " g e n d e r " : 2 , " i d " : 1 3 2 5 8 5 , " j o b " : " a r t d i r e c t i o n " , " n a m e " : " n i c k b a s s e t t " } , { " c r e d i t _ i d " : " 5 3 9 c 4 9 0 3 c 3 a 3 6 8 6 5 3 d 0 0 1 a 7 4 " , " d e p a r t m e n t " : " a r t " , " g e n d e r " : 0 , " i d " : 1 3 2 5 9 6 , " j o b " : " a r t d i r e c t i o n " , " n a m e " : " j i l l c o r m a c k " } , { " c r e d i t _ i d " : " 5 3 9 c 4 9 6 7 c 3 a 3 6 8 6 5 3 d 0 0 1 a 9 4 " , " d e p a r t m e n t " : " a r t " , " g e n d e r " : 0 , " i d " : 1 3 2 6 0 4 , " j o b " : " a r t d i r e c t i o n " , " n a m e " : " a n d y m c l a r e n " } , { " c r e d i t _ i d " : " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 4 5 " , " d e p a r t m e n t " : " c r e w " , " g e n d e r " : 0 , " i d " : 2 3 6 6 9 6 , " j o b " : " m o t i o n c a p t u r e a r t i s t " , " n a m e " : " t e r r y n o t a r y " } , { " c r e d i t _ i d " : " 5 4 9 5 9 e 0 2 c 3 a 3 6 8 0 f c 6 0 0 2 7 d 2 " , " d e p a r t m e n t " : " c r e w " , " g e n d e r " : 2 , " i d " : 9 5 6 1 9 8 , " j o b " : " s t u n t c o o r d i n a t o r " , " n a m e " : " g a r r e t t w a r r e n " } , { " c r e d i t _ i d " : " 5 4 9 5 9 c a 3 c 3 a 3 6 8 6 a e 3 0 0 4 3 8 c " , " d e p a r t m e n t " : " v i s u a l e f f e c t s " , " g e n d e r " : 2 , " i d " : 9 5 7 8 7 4 , " j o b " : " v i s u a l e f f e c t s s u p e r v i s o r " , " n a m e " : " j o n a t h a n r o t h b a r t " } , { " c r e d i t _ i d " : " 5 7 0 b 6 f 5 1 9 2 5 1 4 1 2 c 7 4 0 0 1 b 2 f " , " d e p a r t m e n t " : " a r t " , " g e n d e r " : 0 , " i d " : 9 5 7 8 8 9 , " j o b " : " s u p e r v i s i n g a r t d i r e c t o r " , " n a m e " : " s t e f a n d e c h a n t " } , { " c r e d i t _ i d " : " 5 7 0 b 6 f 6 2 c 3 a 3 6 8 0 b 7 7 0 0 7 4 6 0 " , " d e p a r t m e n t " : " a r t " , " g e n d e r " : 2 , " i d " : 9 5 9 5 5 5 , " j o b " : " s u p e r v i s i n g a r t d i r e c t o r " , " n a m e " : " t o d d c h e r n i a w s k y " } , { " c r e d i t _ i d " : " 5 3 9 c 4 a 3 a c 3 a 3 6 8 1 0 d a 0 0 2 1 c c " , " d e p a r t m e n t " : " p r o d u c t i o n " , " g e n d e r " : 0 , " i d " : 1 0 1 6 1 7 7 , " j o b " : " c a s t i n g " , " n a m e " : " m i r a n d a r i v e r s " } , { " c r e d i t _ i d " : " 5 3 9 c 4 8 2 c c 3 a 3 6 8 1 0 c 1 0 0 2 0 6 2 " , " d e p a r t m e n t " : " a r t " , " g e n d e r " : 0 , " i d " : 1 0 3 2 5 3 6 , " j o b " : " p r o d u c t i o n d e s i g n " , " n a m e " : " r o b e r t s t r o m b e r g " } , { " c r e d i t _ i d " : " 5 3 9 c 4 b 6 5 c 3 a 3 6 8 1 0 c 9 0 0 2 1 2 5 " , " d e p a r t m e n t " : " c o s t u m e & m a k e - u p " , " g e n d e r " : 2 , " i d " : 1 0 7 1 6 8 0 , " j o b " : " c o s t u m e d e s i g n " , " n a m e " : " j o h n h a r d i n g " } , { " c r e d i t _ i d " : " 5 4 9 5 9 e 6 6 9 2 5 1 4 1 3 0 f c 0 0 2 e 4 e " , " d e p a r t m e n t " : " c a m e r a " , " g e n d e r " : 0 , " i d " : 1 1 7 7 3 6 4 , " j o b " : " s t e a d i c a m o p e r a t o r " , " n a m e " : " r o b e r t o d e a n g e l i s " } , { " c r e d i t _ i d " : " 5 3 9 c 4 9 f 1 c 3 a 3 6 8 6 5 3 d 0 0 1 a a c " , " d e p a r t m e n t " : " c o s t u m e & m a k e - u p " , " g e n d e r " : 2 , " i d " : 1 2 0 2 8 5 0 , " j o b " : " m a k e u p d e p a r t m e n t h e a d " , " n a m e " : " m i k e s m i t h s o n " } , { " c r e d i t _ i d " : " 5 4 9 5 9 9 9 e c 3 a 3 6 8 6 a e 1 0 0 4 6 0 c " , " d e p a r t m e n t " : " v i s u a l e f f e c t s " , " g e n d e r " : 0 , " i d " : 1 2 0 4 6 6 8 , " j o b " : " v i s u a l e f f e c t s p r o d u c e r " , " n a m e " : " a l a i n l a l a n n e " } , { " c r e d i t _ i d " : " 5 4 9 5 9 c d f c 3 a 3 6 8 1 1 5 3 0 0 2 7 2 9 " , " d e p a r t m e n t " : " v i s u a l e f f e c t s " , " g e n d e r " : 0 , " i d " : 1 2 0 6 4 1 0 , " j o b " : " v i s u a l e f f e c t s s u p e r v i s o r " , " n a m e " : " l u c a s s a l t o n " } , { " c r e d i t _ i d " : " 5 4 9 5 9 6 2 3 9 2 5 1 4 1 7 a 8 1 0 0 1 e a e " , " d e p a r t m e n t " : " c r e w " , " g e n d e r " : 0 , " i d " : 1 2 3 4 2 6 6 , " j o b " : " p o s t p r o d u c t i o n s u p e r v i s o r " , " n a m e " : " j a n a c e t a s h j i a n " } , { " c r e d i t _ i d " : " 5 4 9 5 9 c 8 5 9 2 5 1 4 1 6 e 1 e 0 0 3 e f e " , " d e p a r t m e n t " : " v i s u a l e f f e c t s " , " g e n d e r " : 0 , " i d " : 1 2 7 1 9 3 2 , " j o b " : " v i s u a l e f f e c t s s u p e r v i s o r " , " n a m e " : " s t e p h e n r o s e n b a u m " } , { " c r e d i t _ i d " : " 5 5 9 2 a f 2 8 c 3 a 3 6 8 7 7 5 a 0 0 1 0 5 f " , " d e p a r t m e n t " : " c o s t u m e & m a k e - u p " , " g e n d e r " : 0 , " i d " : 1 3 1 0 0 6 4 , " j o b " : " m a k e u p a r t i s t " , " n a m e " : " f r a n k i e k a r e n a " } , { " c r e d i t _ i d " : " 5 3 9 c 4 a d f c 3 a 3 6 8 1 0 e 3 0 0 2 0 3 b " , " d e p a r t m e n t " : " c o s t u m e & m a k e - u p " , " g e n d e r " : 1 , " i d " : 1 3 1 9 8 4 4 , " j o b " : " c o s t u m e s u p e r v i s o r " , " n a m e " : " l i s a l o v a a s " } , { " c r e d i t _ i d " : " 5 4 9 5 9 b 5 7 9 2 5 1 4 1 6 e 2 b 0 0 4 3 7 1 " , " d e p a r t m e n t " : " v i s u a l e f f e c t s " , " g e n d e r " : 0 , " i d " : 1 3 2 7 0 2 8 , " j o b " : " v i s u a l e f f e c t s s u p e r v i s o r " , " n a m e " : " j o n a t h a n f a w k n e r " } , { " c r e d i t _ i d " : " 5 3 9 c 4 8 a 7 c 3 a 3 6 8 1 0 b 5 0 0 1 f a 7 " , " d e p a r t m e n t " : " a r t " , " g e n d e r " : 0 , " i d " : 1 3 3 0 5 6 1 , " j o b " : " a r t d i r e c t i o n " , " n a m e " : " r o b e r t b a v i n " } , { " c r e d i t _ i d " : " 5 3 9 c 4 a 7 1 c 3 a 3 6 8 1 0 d a 0 0 2 1 e 0 " , " d e p a r t m e n t " : " c o s t u m e & m a k e - u p " , " g e n d e r " : 0 , " i d " : 1 3 3 0 5 6 7 , " j o b " : " c o s t u m e s u p e r v i s o r " , " n a m e " : " a n t h o n y a l m a r a z " } , { " c r e d i t _ i d " : " 5 3 9 c 4 a 8 a c 3 a 3 6 8 1 0 b a 0 0 2 1 e 4 " , " d e p a r t m e n t " : " c o s t u m e & m a k e - u p " , " g e n d e r " : 0 , " i d " : 1 3 3 0 5 7 0 , " j o b " : " c o s t u m e s u p e r v i s o r " , " n a m e " : " c a r o l y n m . f e n t o n " } , { " c r e d i t _ i d " : " 5 3 9 c 4 a b 6 c 3 a 3 6 8 1 0 d a 0 0 2 1 f 0 " , " d e p a r t m e n t " : " c o s t u m e & m a k e - u p " , " g e n d e r " : 0 , " i d " : 1 3 3 0 5 7 4 , " j o b " : " c o s t u m e s u p e r v i s o r " , " n a m e " : " b e t h k o e n i g s b e r g " } , { " c r e d i t _ i d " : " 5 4 4 9 1 a b 7 0 e 0 a 2 6 7 4 8 0 0 0 1 b a 2 " , " d e p a r t m e n t " : " a r t " , " g e n d e r " : 0 , " i d " : 1 3 3 6 1 9 1 , " j o b " : " s e t d e s i g n e r " , " n a m e " : " s a m p a g e " } , { " c r e d i t _ i d " : " 5 4 4 9 1 9 d 9 c 3 a 3 6 8 0 f c 3 0 0 1 8 b d " , " d e p a r t m e n t " : " a r t " , " g e n d e r " : 0 , " i d " : 1 3 3 9 4 4 1 , " j o b " : " s e t d e s i g n e r " , " n a m e " : " t e x k a d o n a g a " } , { " c r e d i t _ i d " : " 5 4 4 9 1 c f 5 0 e 0 a 2 6 7 4 8 3 0 0 1 b 0 c " , " d e p a r t m e n t " : " e d i t i n g " , " g e n d e r " : 0 , " i d " : 1 3 5 2 4 2 2 , " j o b " : " d i a l o g u e e d i t o r " , " n a m e " : " k i m f o s c a t o " } , { " c r e d i t _ i d " : " 5 4 4 9 1 9 f 4 0 e 0 a 2 6 7 4 8 c 0 0 1 b 0 9 " , " d e p a r t m e n t " : " a r t " , " g e n d e r " : 0 , " i d " : 1 3 5 2 9 6 2 , " j o b " : " s e t d e s i g n e r " , " n a m e " : " t a m m y s . l e e " } , { " c r e d i t _ i d " : " 5 4 9 5 a 1 1 5 c 3 a 3 6 8 0 f f 5 0 0 2 d 7 1 " , " d e p a r t m e n t " : " c r e w " , " g e n d e r " : 0 , " i d " : 1 3 5 7 0 7 0 , " j o b " : " t r a n s p o r t a t i o n c o o r d i n a t o r " , " n a m e " : " d e n n y c a i r a " } , { " c r e d i t _ i d " : " 5 4 9 5 a 1 2 f 9 2 5 1 4 1 3 0 f c 0 0 2 e 9 4 " , " d e p a r t m e n t " : " c r e w " , " g e n d e r " : 0 , " i d " : 1 3 5 7 0 7 1 , " j o b " : " t r a n s p o r t a t i o n c o o r d i n a t o r " , " n a m e " : " j a m e s w a i t k u s " } , { " c r e d i t _ i d " : " 5 4 9 5 9 7 6 f c 3 a 3 6 8 1 1 5 3 0 0 2 6 b 0 " , " d e p a r t m e n t " : " s o u n d " , " g e n d e r " : 0 , " i d " : 1 3 6 0 1 0 3 , " j o b " : " s u p e r v i s i n g s o u n d e d i t o r " , " n a m e " : " a d d i s o n t e a g u e " } , { " c r e d i t _ i d " : " 5 4 4 9 1 8 3 7 c 3 a 3 6 8 0 f b 1 0 0 1 c 5 a " , " d e p a r t m e n t " : " a r t " , " g e n d e r " : 2 , " i d " : 1 3 7 6 8 8 7 , " j o b " : " s e t d e s i g n e r " , " n a

In [146]:
new_df['tags']=new_df['tags'].apply(lambda x: x.lower())

C:\Users\HP\AppData\Local\Temp\ipykernel_10676\2543325826.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags']=new_df['tags'].apply(lambda x: x.lower())

In [147]:
new_df.head()

,movie_id,title,tags
0,19995,Avatar,"in the 22nd century, a parapleg marin is dispa..."
1,285,Pirates of the Caribbean: At World's End,"captain barbossa, long believ to be dead, ha c..."
2,206647,Spectre,a cryptic messag from bond’ past send him on a...
3,49026,The Dark Knight Rises,follow the death of district attorney harvey d...
4,49529,John Carter,"john carter is a war-weary, former militari ca..."

In [148]:
import nltk

In [149]:
from nltk.stem.porter import PorterStemmer
ps=PorterStemmer()

In [150]:
def stem(text):
    y=[]
    for i in text.split():
        y.append(ps.stem(i))
    return " ".join(y)

In [151]:
new_df['tags'][0]

'in the 22nd century, a parapleg marin is dispatch to the moon pandora on a uniqu mission, but becom torn between follow order and protect an alien civilization. action adventur fantasi sciencefict cultureclash futur spacewar spacecoloni societi spacetravel futurist romanc space alien tribe alienplanet cgi marin soldier battl loveaffair antiwar powerrel mindandsoul 3d samworthington zoesaldana sigourneyweav [ { " c r e d i t _ i d " : " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 2 3 " , " d e p a r t m e n t " : " e d i t i n g " , " g e n d e r " : 0 , " i d " : 1 7 2 1 , " j o b " : " e d i t o r " , " n a m e " : " s t e p h e n e . r i v k i n " } , { " c r e d i t _ i d " : " 5 3 9 c 4 7 e c c 3 a 3 6 8 1 0 e 3 0 0 1 f 8 7 " , " d e p a r t m e n t " : " a r t " , " g e n d e r " : 2 , " i d " : 4 9 6 , " j o b " : " p r o d u c t i o n d e s i g n " , " n a m e " : " r i c k c a r t e r " } , { " c r e d i t _ i d " : " 5 4 4 9 1 c 8 9 c 3 a 3 6 8 0 f b 4 0 0 1 c f 7 " , " d e p a r t m e n t " : " s o u n d " , " g e n d e r " : 0 , " i d " : 9 0 0 , " j o b " : " s o u n d d e s i g n e r " , " n a m e " : " c h r i s t o p h e r b o y e s " } , { " c r e d i t _ i d " : " 5 4 4 9 1 c b 7 0 e 0 a 2 6 7 4 8 0 0 0 1 b d 0 " , " d e p a r t m e n t " : " s o u n d " , " g e n d e r " : 0 , " i d " : 9 0 0 , " j o b " : " s u p e r v i s i n g s o u n d e d i t o r " , " n a m e " : " c h r i s t o p h e r b o y e s " } , { " c r e d i t _ i d " : " 5 3 9 c 4 a 4 c c 3 a 3 6 8 1 0 c 9 0 0 2 1 0 1 " , " d e p a r t m e n t " : " p r o d u c t i o n " , " g e n d e r " : 1 , " i d " : 1 2 6 2 , " j o b " : " c a s t i n g " , " n a m e " : " m a l i f i n n " } , { " c r e d i t _ i d " : " 5 5 4 4 e e 3 b 9 2 5 1 4 1 4 9 9 f 0 0 0 8 f c " , " d e p a r t m e n t " : " s o u n d " , " g e n d e r " : 2 , " i d " : 1 7 2 9 , " j o b " : " o r i g i n a l m u s i c c o m p o s e r " , " n a m e " : " j a m e s h o r n e r " } , { " c r e d i t _ i d " : " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c 9 c 3 " , " d e p a r t m e n t " : " d i r e c t i n g " , " g e n d e r " : 2 , " i d " : 2 7 1 0 , " j o b " : " d i r e c t o r " , " n a m e " : " j a m e s c a m e r o n " } , { " c r e d i t _ i d " : " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c 9 d 9 " , " d e p a r t m e n t " : " w r i t i n g " , " g e n d e r " : 2 , " i d " : 2 7 1 0 , " j o b " : " w r i t e r " , " n a m e " : " j a m e s c a m e r o n " } , { " c r e d i t _ i d " : " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 1 7 " , " d e p a r t m e n t " : " e d i t i n g " , " g e n d e r " : 2 , " i d " : 2 7 1 0 , " j o b " : " e d i t o r " , " n a m e " : " j a m e s c a m e r o n " } , { " c r e d i t _ i d " : " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 2 9 " , " d e p a r t m e n t " : " p r o d u c t i o n " , " g e n d e r " : 2 , " i d " : 2 7 1 0 , " j o b " : " p r o d u c e r " , " n a m e " : " j a m e s c a m e r o n " } , { " c r e d i t _ i d " : " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 3 f " , " d e p a r t m e n t " : " w r i t i n g " , " g e n d e r " : 2 , " i d " : 2 7 1 0 , " j o b " : " s c r e e n p l a y " , " n a m e " : " j a m e s c a m e r o n " } , { " c r e d i t _ i d " : " 5 3 9 c 4 9 8 7 c 3 a 3 6 8 1 0 b a 0 0 2 1 a 4 " , " d e p a r t m e n t " : " a r t " , " g e n d e r " : 2 , " i d " : 7 2 3 6 , " j o b " : " a r t d i r e c t i o n " , " n a m e " : " a n d r e w m e n z i e s " } , { " c r e d i t _ i d " : " 5 4 9 5 9 8 c 3 c 3 a 3 6 8 6 a e 9 0 0 4 3 8 3 " , " d e p a r t m e n t " : " v i s u a l e f f e c t s " , " g e n d e r " : 0 , " i d " : 6 6 9 0 , " j o b " : " v i s u a l e f f e c t s p r o d u c e r " , " n a m e " : " j i l l b r o o k s " } , { " c r e d i t _ i d " : " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 4 b " , " d e p a r t m e n t " : " p r o d u c t i o n " , " g e n d e r " : 1 , " i d " : 6 3 4 7 , " j o b " : " c a s t i n g " , " n a m e " : " m a r g e r y s i m k i n " } , { " c r e d i t _ i d " : " 5 7 0 b 6 f 4 1 9 2 5 1 4 1 7 d a 7 0 0 3 2 f e " , " d e p a r t m e n t " : " a r t " , " g e n d e r " : 2 , " i d " : 6 8 7 8 , " j o b " : " s u p e r v i s i n g a r t d i r e c t o r " , " n a m e " : " k e v i n i s h i o k a " } , { " c r e d i t _ i d " : " 5 4 9 5 a 0 f a c 3 a 3 6 8 6 a e 9 0 0 4 4 6 8 " , " d e p a r t m e n t " : " s o u n d " , " g e n d e r " : 0 , " i d " : 6 8 8 3 , " j o b " : " m u s i c e d i t o r " , " n a m e " : " d i c k b e r n s t e i n " } , { " c r e d i t _ i d " : " 5 4 9 5 9 7 0 6 c 3 a 3 6 8 6 a f 3 0 0 3 e 8 1 " , " d e p a r t m e n t " : " s o u n d " , " g e n d e r " : 0 , " i d " : 8 1 5 9 , " j o b " : " s o u n d e f f e c t s e d i t o r " , " n a m e " : " s h a n n o n m i l l s " } , { " c r e d i t _ i d " : " 5 4 4 9 1 d 5 8 c 3 a 3 6 8 0 f b 1 0 0 1 c c b " , " d e p a r t m e n t " : " s o u n d " , " g e n d e r " : 0 , " i d " : 8 1 6 0 , " j o b " : " f o l e y " , " n a m e " : " d e n n i e t h o r p e " } , { " c r e d i t _ i d " : " 5 4 4 9 1 d 6 c c 3 a 3 6 8 0 f a 5 0 0 1 b 2 c " , " d e p a r t m e n t " : " s o u n d " , " g e n d e r " : 0 , " i d " : 8 1 6 3 , " j o b " : " f o l e y " , " n a m e " : " j a n a v a n c e " } , { " c r e d i t _ i d " : " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 5 7 " , " d e p a r t m e n t " : " c o s t u m e & m a k e - u p " , " g e n d e r " : 1 , " i d " : 8 5 2 7 , " j o b " : " c o s t u m e d e s i g n " , " n a m e " : " d e b o r a h l y n n s c o t t " } , { " c r e d i t _ i d " : " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 2 f " , " d e p a r t m e n t " : " p r o d u c t i o n " , " g e n d e r " : 2 , " i d " : 8 5 2 9 , " j o b " : " p r o d u c e r " , " n a m e " : " j o n l a n d a u " } , { " c r e d i t _ i d " : " 5 3 9 c 4 9 3 7 c 3 a 3 6 8 1 0 b a 0 0 2 1 9 4 " , " d e p a r t m e n t " : " a r t " , " g e n d e r " : 0 , " i d " : 9 6 1 8 , " j o b " : " a r t d i r e c t i o n " , " n a m e " : " s e a n h a w o r t h " } , { " c r e d i t _ i d " : " 5 3 9 c 4 9 b 6 c 3 a 3 6 8 1 0 c 1 0 0 2 0 e 6 " , " d e p a r t m e n t " : " a r t " , " g e n d e r " : 1 , " i d " : 1 2 6 5 3 , " j o b " : " s e t d e c o r a t i o n " , " n a m e " : " k i m s i n c l a i r " } , { " c r e d i t _ i d " : " 5 7 0 b 6 f 2 f 9 2 5 1 4 1 3 a 0 e 0 0 0 2 0 d " , " d e p a r t m e n t " : " a r t " , " g e n d e r " : 1 , " i d " : 1 2 6 5 3 , " j o b " : " s u p e r v i s i n g a r t d i r e c t o r " , " n a m e " : " k i m s i n c l a i r " } , { " c r e d i t _ i d " : " 5 4 4 9 1 a 6 c 0 e 0 a 2 6 7 4 8 c 0 0 1 b 1 9 " , " d e p a r t m e n t " : " a r t " , " g e n d e r " : 2 , " i d " : 1 4 3 5 0 , " j o b " : " s e t d e s i g n e r " , " n a m e " : " r i c h a r d f . m a y s " } , { " c r e d i t _ i d " : " 5 6 9 2 8 c f 4 c 3 a 3 6 8 4 c f f 0 0 2 5 c 4 " , " d e p a r t m e n t " : " p r o d u c t i o n " , " g e n d e r " : 1 , " i d " : 2 0 2 9 4 , " j o b " : " e x e c u t i v e p r o d u c e r " , " n a m e " : " l a e t a k a l o g r i d i s " } , { " c r e d i t _ i d " : " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 5 1 " , " d e p a r t m e n t " : " c o s t u m e & m a k e - u p " , " g e n d e r " : 0 , " i d " : 1 7 6 7 5 , " j o b " : " c o s t u m e d e s i g n " , " n a m e " : " m a y e s c . r u b e o " } , { " c r e d i t _ i d " : " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 1 1 " , " d e p a r t m e n t " : " c a m e r a " , " g e n d e r " : 2 , " i d " : 1 8 2 6 5 , " j o b " : " d i r e c t o r o f p h o t o g r a p h y " , " n a m e " : " m a u r o f i o r e " } , { " c r e d i t _ i d " : " 5 4 4 9 1 9 4 d 0 e 0 a 2 6 7 4 8 f 0 0 1 b 3 9 " , " d e p a r t m e n t " : " a r t " , " g e n d e r " : 0 , " i d " : 4 2 2 8 1 , " j o b " : " s e t d e s i g n e r " , " n a m e " : " s c o t t h e r b e r t s o n " } , { " c r e d i t _ i d " : " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 0 5 " , " d e p a r t m e n t " : " c r e w " , " g e n d e r " : 0 , " i d " : 4 2 2 8 8 , " j o b " : " s t u n t s " , " n a m e " : " w o o d y s c h u l t z " } , { " c r e d i t _ i d " : " 5 5 9 2 a e f b 9 2 5 1 4 1 5 2 d e 0 0 1 0 f 5 " , " d e p a r t m e n t " : " c o s t u m e & m a k e - u p " , " g e n d e r " : 0 , " i d " : 2 9 0 6 7 , " j o b " : " m a k e u p a r t i s t " , " n a m e " : " l i n d a d e v e t t a " } , { " c r e d i t _ i d " : " 5 5 9 2 a f a 4 9 2 5 1 4 1 5 2 d e 0 0 1 1 2 c " , " d e p a r t m e n t " : " c o s t u m e & m a k e - u p " , " g e n d e r " : 0 , " i d " : 2 9 0 6 7 , " j o b " : " h a i r s t y l i s t " , " n a m e " : " l i n d a d e v e t t a " } , { " c r e d i t _ i d " : " 5 4 9 5 9 e d 5 9 2 5 1 4 1 3 0 f c 0 0 2 e 5 d " , " d e p a r t m e n t " : " c a m e r a " , " g e n d e r " : 2 , " i d " : 3 3 3 0 2 , " j o b " : " c a m e r a o p e r a t o r " , " n a m e " : " r i c h a r d b l u c k " } , { " c r e d i t _ i d " : " 5 3 9 c 4 8 9 1 c 3 a 3 6 8 1 0 b a 0 0 2 1 4 7 " , " d e p a r t m e n t " : " a r t " , " g e n d e r " : 2 , " i d " : 3 3 3 0 3 , " j o b " : " a r t d i r e c t i o n " , " n a m e " : " s i m o n b r i g h t " } , { " c r e d i t _ i d " : " 5 4 9 5 9 c 0 6 9 2 5 1 4 1 7 a 8 1 0 0 1 f 3 a " , " d e p a r t m e n t " : " v i s u a l e f f e c t s " , " g e n d e r " : 0 , " i d " : 1 1 3 1 4 5 , " j o b " : " v i s u a l e f f e c t s s u p e r v i s o r " , " n a m e " : " r i c h a r d m a r t i n " } , { " c r e d i t _ i d " : " 5 4 9 5 9 a 0 d c 3 a 3 6 8 0 f f 5 0 0 2 c 8 d " , " d e p a r t m e n t " : " c r e w " , " g e n d e r " : 2 , " i d " : 5 8 1 8 8 , " j o b " : " v i s u a l e f f e c t s e d i t o r " , " n a m e " : " s t e v e r . m o o r e " } , { " c r e d i t _ i d " : " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 1 d " , " d e p a r t m e n t " : " e d i t i n g " , " g e n d e r " : 2 , " i d " : 5 8 8 7 1 , " j o b " : " e d i t o r " , " n a m e " : " j o h n r e f o u a " } , { " c r e d i t _ i d " : " 5 4 4 9 1 a 4 d c 3 a 3 6 8 0 f c 3 0 0 1 8 c a " , " d e p a r t m e n t " : " a r t " , " g e n d e r " : 0 , " i d " : 9 2 3 5 9 , " j o b " : " s e t d e s i g n e r " , " n a m e " : " k a r l j . m a r t i n " } , { " c r e d i t _ i d " : " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 3 5 " , " d e p a r t m e n t " : " c a m e r a " , " g e n d e r " : 1 , " i d " : 7 2 2 0 1 , " j o b " : " d i r e c t o r o f p h o t o g r a p h y " , " n a m e " : " c h i l i n g l i n " } , { " c r e d i t _ i d " : " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c 9 f f " , " d e p a r t m e n t " : " c r e w " , " g e n d e r " : 0 , " i d " : 8 9 7 1 4 , " j o b " : " s t u n t s " , " n a m e " : " i l r a m c h o i " } , { " c r e d i t _ i d " : " 5 4 9 5 9 c 5 2 9 2 5 1 4 1 6 e 2 b 0 0 4 3 9 4 " , " d e p a r t m e n t " : " v i s u a l e f f e c t s " , " g e n d e r " : 2 , " i d " : 9 3 2 1 4 , " j o b " : " v i s u a l e f f e c t s s u p e r v i s o r " , " n a m e " : " s t e v e n q u a l e " } , { " c r e d i t _ i d " : " 5 4 4 9 1 e d f 0 e 0 a 2 6 7 4 8 9 0 0 1 c 3 7 " , " d e p a r t m e n t " : " c r e w " , " g e n d e r " : 1 , " i d " : 1 2 2 6 0 7 , " j o b " : " d i a l e c t c o a c h " , " n a m e " : " c a r l a m e y e r " } , { " c r e d i t _ i d " : " 5 3 9 c 4 8 5 b c 3 a 3 6 8 6 5 3 d 0 0 1 a 3 a " , " d e p a r t m e n t " : " a r t " , " g e n d e r " : 2 , " i d " : 1 3 2 5 8 5 , " j o b " : " a r t d i r e c t i o n " , " n a m e " : " n i c k b a s s e t t " } , { " c r e d i t _ i d " : " 5 3 9 c 4 9 0 3 c 3 a 3 6 8 6 5 3 d 0 0 1 a 7 4 " , " d e p a r t m e n t " : " a r t " , " g e n d e r " : 0 , " i d " : 1 3 2 5 9 6 , " j o b " : " a r t d i r e c t i o n " , " n a m e " : " j i l l c o r m a c k " } , { " c r e d i t _ i d " : " 5 3 9 c 4 9 6 7 c 3 a 3 6 8 6 5 3 d 0 0 1 a 9 4 " , " d e p a r t m e n t " : " a r t " , " g e n d e r " : 0 , " i d " : 1 3 2 6 0 4 , " j o b " : " a r t d i r e c t i o n " , " n a m e " : " a n d y m c l a r e n " } , { " c r e d i t _ i d " : " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 4 5 " , " d e p a r t m e n t " : " c r e w " , " g e n d e r " : 0 , " i d " : 2 3 6 6 9 6 , " j o b " : " m o t i o n c a p t u r e a r t i s t " , " n a m e " : " t e r r y n o t a r y " } , { " c r e d i t _ i d " : " 5 4 9 5 9 e 0 2 c 3 a 3 6 8 0 f c 6 0 0 2 7 d 2 " , " d e p a r t m e n t " : " c r e w " , " g e n d e r " : 2 , " i d " : 9 5 6 1 9 8 , " j o b " : " s t u n t c o o r d i n a t o r " , " n a m e " : " g a r r e t t w a r r e n " } , { " c r e d i t _ i d " : " 5 4 9 5 9 c a 3 c 3 a 3 6 8 6 a e 3 0 0 4 3 8 c " , " d e p a r t m e n t " : " v i s u a l e f f e c t s " , " g e n d e r " : 2 , " i d " : 9 5 7 8 7 4 , " j o b " : " v i s u a l e f f e c t s s u p e r v i s o r " , " n a m e " : " j o n a t h a n r o t h b a r t " } , { " c r e d i t _ i d " : " 5 7 0 b 6 f 5 1 9 2 5 1 4 1 2 c 7 4 0 0 1 b 2 f " , " d e p a r t m e n t " : " a r t " , " g e n d e r " : 0 , " i d " : 9 5 7 8 8 9 , " j o b " : " s u p e r v i s i n g a r t d i r e c t o r " , " n a m e " : " s t e f a n d e c h a n t " } , { " c r e d i t _ i d " : " 5 7 0 b 6 f 6 2 c 3 a 3 6 8 0 b 7 7 0 0 7 4 6 0 " , " d e p a r t m e n t " : " a r t " , " g e n d e r " : 2 , " i d " : 9 5 9 5 5 5 , " j o b " : " s u p e r v i s i n g a r t d i r e c t o r " , " n a m e " : " t o d d c h e r n i a w s k y " } , { " c r e d i t _ i d " : " 5 3 9 c 4 a 3 a c 3 a 3 6 8 1 0 d a 0 0 2 1 c c " , " d e p a r t m e n t " : " p r o d u c t i o n " , " g e n d e r " : 0 , " i d " : 1 0 1 6 1 7 7 , " j o b " : " c a s t i n g " , " n a m e " : " m i r a n d a r i v e r s " } , { " c r e d i t _ i d " : " 5 3 9 c 4 8 2 c c 3 a 3 6 8 1 0 c 1 0 0 2 0 6 2 " , " d e p a r t m e n t " : " a r t " , " g e n d e r " : 0 , " i d " : 1 0 3 2 5 3 6 , " j o b " : " p r o d u c t i o n d e s i g n " , " n a m e " : " r o b e r t s t r o m b e r g " } , { " c r e d i t _ i d " : " 5 3 9 c 4 b 6 5 c 3 a 3 6 8 1 0 c 9 0 0 2 1 2 5 " , " d e p a r t m e n t " : " c o s t u m e & m a k e - u p " , " g e n d e r " : 2 , " i d " : 1 0 7 1 6 8 0 , " j o b " : " c o s t u m e d e s i g n " , " n a m e " : " j o h n h a r d i n g " } , { " c r e d i t _ i d " : " 5 4 9 5 9 e 6 6 9 2 5 1 4 1 3 0 f c 0 0 2 e 4 e " , " d e p a r t m e n t " : " c a m e r a " , " g e n d e r " : 0 , " i d " : 1 1 7 7 3 6 4 , " j o b " : " s t e a d i c a m o p e r a t o r " , " n a m e " : " r o b e r t o d e a n g e l i s " } , { " c r e d i t _ i d " : " 5 3 9 c 4 9 f 1 c 3 a 3 6 8 6 5 3 d 0 0 1 a a c " , " d e p a r t m e n t " : " c o s t u m e & m a k e - u p " , " g e n d e r " : 2 , " i d " : 1 2 0 2 8 5 0 , " j o b " : " m a k e u p d e p a r t m e n t h e a d " , " n a m e " : " m i k e s m i t h s o n " } , { " c r e d i t _ i d " : " 5 4 9 5 9 9 9 e c 3 a 3 6 8 6 a e 1 0 0 4 6 0 c " , " d e p a r t m e n t " : " v i s u a l e f f e c t s " , " g e n d e r " : 0 , " i d " : 1 2 0 4 6 6 8 , " j o b " : " v i s u a l e f f e c t s p r o d u c e r " , " n a m e " : " a l a i n l a l a n n e " } , { " c r e d i t _ i d " : " 5 4 9 5 9 c d f c 3 a 3 6 8 1 1 5 3 0 0 2 7 2 9 " , " d e p a r t m e n t " : " v i s u a l e f f e c t s " , " g e n d e r " : 0 , " i d " : 1 2 0 6 4 1 0 , " j o b " : " v i s u a l e f f e c t s s u p e r v i s o r " , " n a m e " : " l u c a s s a l t o n " } , { " c r e d i t _ i d " : " 5 4 9 5 9 6 2 3 9 2 5 1 4 1 7 a 8 1 0 0 1 e a e " , " d e p a r t m e n t " : " c r e w " , " g e n d e r " : 0 , " i d " : 1 2 3 4 2 6 6 , " j o b " : " p o s t p r o d u c t i o n s u p e r v i s o r " , " n a m e " : " j a n a c e t a s h j i a n " } , { " c r e d i t _ i d " : " 5 4 9 5 9 c 8 5 9 2 5 1 4 1 6 e 1 e 0 0 3 e f e " , " d e p a r t m e n t " : " v i s u a l e f f e c t s " , " g e n d e r " : 0 , " i d " : 1 2 7 1 9 3 2 , " j o b " : " v i s u a l e f f e c t s s u p e r v i s o r " , " n a m e " : " s t e p h e n r o s e n b a u m " } , { " c r e d i t _ i d " : " 5 5 9 2 a f 2 8 c 3 a 3 6 8 7 7 5 a 0 0 1 0 5 f " , " d e p a r t m e n t " : " c o s t u m e & m a k e - u p " , " g e n d e r " : 0 , " i d " : 1 3 1 0 0 6 4 , " j o b " : " m a k e u p a r t i s t " , " n a m e " : " f r a n k i e k a r e n a " } , { " c r e d i t _ i d " : " 5 3 9 c 4 a d f c 3 a 3 6 8 1 0 e 3 0 0 2 0 3 b " , " d e p a r t m e n t " : " c o s t u m e & m a k e - u p " , " g e n d e r " : 1 , " i d " : 1 3 1 9 8 4 4 , " j o b " : " c o s t u m e s u p e r v i s o r " , " n a m e " : " l i s a l o v a a s " } , { " c r e d i t _ i d " : " 5 4 9 5 9 b 5 7 9 2 5 1 4 1 6 e 2 b 0 0 4 3 7 1 " , " d e p a r t m e n t " : " v i s u a l e f f e c t s " , " g e n d e r " : 0 , " i d " : 1 3 2 7 0 2 8 , " j o b " : " v i s u a l e f f e c t s s u p e r v i s o r " , " n a m e " : " j o n a t h a n f a w k n e r " } , { " c r e d i t _ i d " : " 5 3 9 c 4 8 a 7 c 3 a 3 6 8 1 0 b 5 0 0 1 f a 7 " , " d e p a r t m e n t " : " a r t " , " g e n d e r " : 0 , " i d " : 1 3 3 0 5 6 1 , " j o b " : " a r t d i r e c t i o n " , " n a m e " : " r o b e r t b a v i n " } , { " c r e d i t _ i d " : " 5 3 9 c 4 a 7 1 c 3 a 3 6 8 1 0 d a 0 0 2 1 e 0 " , " d e p a r t m e n t " : " c o s t u m e & m a k e - u p " , " g e n d e r " : 0 , " i d " : 1 3 3 0 5 6 7 , " j o b " : " c o s t u m e s u p e r v i s o r " , " n a m e " : " a n t h o n y a l m a r a z " } , { " c r e d i t _ i d " : " 5 3 9 c 4 a 8 a c 3 a 3 6 8 1 0 b a 0 0 2 1 e 4 " , " d e p a r t m e n t " : " c o s t u m e & m a k e - u p " , " g e n d e r " : 0 , " i d " : 1 3 3 0 5 7 0 , " j o b " : " c o s t u m e s u p e r v i s o r " , " n a m e " : " c a r o l y n m . f e n t o n " } , { " c r e d i t _ i d " : " 5 3 9 c 4 a b 6 c 3 a 3 6 8 1 0 d a 0 0 2 1 f 0 " , " d e p a r t m e n t " : " c o s t u m e & m a k e - u p " , " g e n d e r " : 0 , " i d " : 1 3 3 0 5 7 4 , " j o b " : " c o s t u m e s u p e r v i s o r " , " n a m e " : " b e t h k o e n i g s b e r g " } , { " c r e d i t _ i d " : " 5 4 4 9 1 a b 7 0 e 0 a 2 6 7 4 8 0 0 0 1 b a 2 " , " d e p a r t m e n t " : " a r t " , " g e n d e r " : 0 , " i d " : 1 3 3 6 1 9 1 , " j o b " : " s e t d e s i g n e r " , " n a m e " : " s a m p a g e " } , { " c r e d i t _ i d " : " 5 4 4 9 1 9 d 9 c 3 a 3 6 8 0 f c 3 0 0 1 8 b d " , " d e p a r t m e n t " : " a r t " , " g e n d e r " : 0 , " i d " : 1 3 3 9 4 4 1 , " j o b " : " s e t d e s i g n e r " , " n a m e " : " t e x k a d o n a g a " } , { " c r e d i t _ i d " : " 5 4 4 9 1 c f 5 0 e 0 a 2 6 7 4 8 3 0 0 1 b 0 c " , " d e p a r t m e n t " : " e d i t i n g " , " g e n d e r " : 0 , " i d " : 1 3 5 2 4 2 2 , " j o b " : " d i a l o g u e e d i t o r " , " n a m e " : " k i m f o s c a t o " } , { " c r e d i t _ i d " : " 5 4 4 9 1 9 f 4 0 e 0 a 2 6 7 4 8 c 0 0 1 b 0 9 " , " d e p a r t m e n t " : " a r t " , " g e n d e r " : 0 , " i d " : 1 3 5 2 9 6 2 , " j o b " : " s e t d e s i g n e r " , " n a m e " : " t a m m y s . l e e " } , { " c r e d i t _ i d " : " 5 4 9 5 a 1 1 5 c 3 a 3 6 8 0 f f 5 0 0 2 d 7 1 " , " d e p a r t m e n t " : " c r e w " , " g e n d e r " : 0 , " i d " : 1 3 5 7 0 7 0 , " j o b " : " t r a n s p o r t a t i o n c o o r d i n a t o r " , " n a m e " : " d e n n y c a i r a " } , { " c r e d i t _ i d " : " 5 4 9 5 a 1 2 f 9 2 5 1 4 1 3 0 f c 0 0 2 e 9 4 " , " d e p a r t m e n t " : " c r e w " , " g e n d e r " : 0 , " i d " : 1 3 5 7 0 7 1 , " j o b " : " t r a n s p o r t a t i o n c o o r d i n a t o r " , " n a m e " : " j a m e s w a i t k u s " } , { " c r e d i t _ i d " : " 5 4 9 5 9 7 6 f c 3 a 3 6 8 1 1 5 3 0 0 2 6 b 0 " , " d e p a r t m e n t " : " s o u n d " , " g e n d e r " : 0 , " i d " : 1 3 6 0 1 0 3 , " j o b " : " s u p e r v i s i n g s o u n d e d i t o r " , " n a m e " : " a d d i s o n t e a g u e " } , { " c r e d i t _ i d " : " 5 4 4 9 1 8 3 7 c 3 a 3 6 8 0 f b 1 0 0 1 c 5 a " , " d e p a r t m e n t " : " a r t " , " g e n d e r " : 2 , " i d " : 1 3 7 6 8 8 7 , " j o b " : " s e t d e s i g n e r " , " n a

In [152]:
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer(max_features=5000,stop_words='english')

In [153]:
vectors=cv.fit_transform(new_df['tags']).toarray()

In [154]:
cv.get_feature_names_out()

array(['000', '007', '10', ..., 'zone', 'zoo', 'zooeydeschanel'],
      shape=(5000,), dtype=object)

In [155]:
from sklearn.metrics.pairwise import cosine_similarity

In [156]:
similarity=cosine_similarity(vectors)

In [157]:
sorted(list(enumerate(similarity[0])),reverse=True,key=lambda x:x[1])[1:6]

[(1214, np.float64(0.29061909685954823)),
 (3728, np.float64(0.26401000024165)),
 (507, np.float64(0.26130213378560535)),
 (539, np.float64(0.2537477434955704)),
 (2405, np.float64(0.2507061052819501))]

In [158]:
similarity[0]

array([1.        , 0.08585457, 0.08718573, ..., 0.04559608, 0.        ,
       0.        ], shape=(4806,))

In [172]:
def recommend(movie):
    movie_index=new_df[new_df['title']==movie].index[0]
    distances=similarity[movie_index]
    movie_list=sorted(list(enumerate(distances)),reverse=True,key=lambda x:x[1])[1:6]
    for i in movie_list:
        print(new_df.iloc[i[0]].title)

In [173]:
new_df.head()

,movie_id,title,tags
0,19995,Avatar,"in the 22nd century, a parapleg marin is dispa..."
1,285,Pirates of the Caribbean: At World's End,"captain barbossa, long believ to be dead, ha c..."
2,206647,Spectre,a cryptic messag from bond’ past send him on a...
3,49026,The Dark Knight Rises,follow the death of district attorney harvey d...
4,49529,John Carter,"john carter is a war-weary, former militari ca..."

In [175]:
recommend('Batman Begins')

The Dark Knight
Batman
Batman
10th & Wolf
The Dark Knight Rises

In [176]:
import pickle

In [179]:
pickle.dump(new_df,open('movies.pkl','wb'))

In [180]:
import os
print(os.getcwd())
print(os.path.exists('movies.pkl'))

C:\Users\HP\ml_projects\movie
True

In [181]:
pickle.dump(new_df.to_dict(),open('movie_dict.pkl','wb'))

In [182]:
pickle.dump(similarity,open('similarity.pkl','wb'))